language: node_js
node_js:
- 4.3.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: aa4b8ab7172d789fd4b380e9f4f8ca72b1112856e981a1b04ffb8b08bd8f43db
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: auWUdp5W7qZXVEGbHt8RIt/yHwmJE7slVVOmWNKRVXLxd/01d9qdwLCIDrskH9UbZ3HWnxwVaPoca3NUU2q06LB/uRV75YUf2NpSr+JQbEitB9/LmdC8vn+GNHlR2JA6rooqo6bTIf7mIinlGo8N+BnH+rNCM7L921qTZJMHDnrhqv7liL97lf2tGxQSJldK4djvblNMKpwwqmIdvpvOriF9p/ktWMKKeokNDyVeDFyQD+hOJ50bf1QB3mkCBlYdwiOwTSjaFXaY7HEYCjL8HsIEMcEgjEXguKo3p5FJzlOn5SZMsNdXtPDBSbeFSdEpq7C1H6czZ+otcDnRbiewVWzesrL+Y/4ieyfS/I9UHUDiHFREihdPfJV228YgluZwrMdugBHdlIK4s5ar93lpuKbU6vF63zmPvTZVXOqqE0X2bnT9qU29zNPGSe4EUwzDKtRscLVoW8yo7krNsnUi46dKi8k1nOf1syfmVNlWnYkU/3ozxtxG7OCgkOeuafwcU7Aq9FFGKzKqcFvgJDIfp1Q9VTuG/vPCjCVL1ENQuEfv1f6z12HsGZPXKh6YsYZetEzSrWklsqlCN7gMb/cyiDv70HsvZu4+RxvPHiwgxYgBofTl62DFkPw6cToVf8fgRLzkqqe7/58Bwi4plt1ILlSwgCqu0JuF4+oxZCu6aCY=
  on:
    tags: true
    repo: yoctore/yocto-mailchimp
before_install: npm install -g grunt-cli
install: npm install
